.Dd ${BUILD_DATE}
.Dt demarkdown 1
.Os
.Sh NAME
.Nm demarkdown
.Nd print markdown without formatting
.Sh SYNOPSIS
.Nm demarkdown
[\fI\,FILE\/\fR]...
.Sh DESCRIPTION
The
.Nm
utility removes all formatting from markdown. This is helpful when performing
text-processing in a pipeline.
.Pp
When content is stripped from the document, line numbers and column positions of the remaining content is preserved.
.Sh "BUGS"
.Nm demarkdown
does not handle tables.
