.Dd ${BUILD_DATE}
.Dt unfold 1
.Os
.Sh NAME
.Nm unfold
.Nd combine lines, reversing the affects of
.Xr fold 1
.Sh SYNOPSIS
.Nm unfold
[\fI\,FILE\/\fR]...
.Sh DESCRIPTION
The
.Nm
utility joins lines to create single-line paragraphs. Input is read from the supplied files or standard in if no files were provided.
.Pp
Leading and trailing whitespace is removed when it interrupts the flow of a paragraph. Duplicate empty lines are also removed.
.Pp
Line breaks are preserved when they they add structure to the content, e.g. when separating list elements.
.Sh "SEE ALSO"
.Xr fold 1
.Sh AUTHORS
.An "Jon Higgs" Aq "jon@altos.au"
