.Dd ${BUILD_DATE}
.Dt org 1
.Os
.Sh NAME
.Nm org
.Nd print the first and last sentence from each paragraph
.Xr fold 1
.Sh SYNOPSIS
.Nm org
[\fI\,FILE\/\fR]...
.Sh DESCRIPTION
The
.Nm org
prints each paragraphs first and last sentences, showing how ideas flow from one paragraph to the next.
.Pp
Lines can be either hard or soft wrapped, but paragraphs must be separated with an empty line and sentences with a period.
.Pp
If no \fI\,FILES\/\fR are supplied, input is read from standard in.
.Sh HISTORY
This tool was inspired by the line:
.Dq org. which prints the first and last sentence of each paragraph, so you can analyze paragraph transitions and the flow of ideas within your writing.
.Pq "UNIX Text Processing, by Dale Dougherty and Tim O'Reilly"
.Pp
It originated under the same name in Writers WorkBench (wwb) by Lorinda Cherry and Nina Macdonald of Bell Labs. This isn't a clone since I've never used or even seen the original.
.Sh AUTHORS
.An "Jon Higgs" Aq "jon@altos.au"
